image: python:3.6-alpine

stages:
  - test
  - pre-release
  - release

before_script:
  - apk update && apk add curl
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - pip install -q tox

flake8:
  script: tox -e flake8

.test: &test
  artifacts:
    paths:
      - .coverage*
    expire_in: 1 hour

py35-djangomaster:
  <<: *test
  image: python:3.5-alpine
  script: tox -e py35-djangomaster
  allow_failure: true

py35-django1.11:
  <<: *test
  image: python:3.5-alpine
  script: tox -e py35-djangomaster

py36-djangomaster:
  <<: *test
  image: python:3.6-alpine
  script: tox -e py36-djangomaster
  allow_failure: true

py36-django1.11:
  <<: *test
  image: python:3.6-alpine
  script: tox -e py36-djangomaster

coverage:
  stage: pre-release
  coverage: '/TOTAL.*\s+(\d+\.?\d+?)\%/'
  script: tox -e coverage-report

release:
  stage: release
  variables:
    TWINE_REPOSITORY_URL: 'https://upload.pypi.org/legacy/'
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip install -q wheel twine
    - python setup.py bdist_wheel sdist
    - twine upload dist/*
  only:
    - tags
    - /^v.*$/
